(defvar t0)
(defvar ap)
(defvar s0)
(defvar io0d)
(defvar io0q)
(defvar io0e)
(defvar io0w)
(defvar io0pu)
(defvar io0pd)
(defvar lfsr)
(defun fibobnacci (k1)
  (let ((a 0) (b 1) (c 1))
    (dotimes (k k1)
      (setq a b)
      (setq b c)
      (setq c (+ a b)))
    c))
(defun test1 (k) (dotimes (k1 k) (setq io0d (fibobnacci (+ 5 k1)))))
(dotimes (tt 2)
(setq lfsr 1)
(let ((a (logand #b1111 lfsr)))
  (setq lfsr 0)
  (setq io0e a)
  (dotimes (k a) (test1 (- (1+ a) k)))))
